// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3rRjBEoiGjF96YGJWNSlmTp5LthcW-w8',
    appId: '1:716539743857:web:7249ae05fe6bfb3c88d5d0',
    messagingSenderId: '716539743857',
    projectId: 'approyalserver',
    authDomain: 'approyalserver.firebaseapp.com',
    storageBucket: 'approyalserver.appspot.com',
    measurementId: 'G-2HQYZ6JGV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-L0g81Mmn14vAmbwjnTOz0dmXcmoF618',
    appId: '1:716539743857:android:54fe2aab28bc3ecd88d5d0',
    messagingSenderId: '716539743857',
    projectId: 'approyalserver',
    storageBucket: 'approyalserver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU1QhP-Leyn1sP369gjHFE-sdtw46VL5U',
    appId: '1:716539743857:ios:8596fc45da934cfc88d5d0',
    messagingSenderId: '716539743857',
    projectId: 'approyalserver',
    storageBucket: 'approyalserver.appspot.com',
    iosClientId: '716539743857-6lpcguu43srb9sfjbnsmu4immac36qld.apps.googleusercontent.com',
    iosBundleId: 'com.example.approyal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU1QhP-Leyn1sP369gjHFE-sdtw46VL5U',
    appId: '1:716539743857:ios:8596fc45da934cfc88d5d0',
    messagingSenderId: '716539743857',
    projectId: 'approyalserver',
    storageBucket: 'approyalserver.appspot.com',
    iosClientId: '716539743857-6lpcguu43srb9sfjbnsmu4immac36qld.apps.googleusercontent.com',
    iosBundleId: 'com.example.approyal',
  );
}
